/obj/machinery/chemical_dispenser/bar_alc/full
	spawn_cartridges = list(
			/obj/item/chems/chem_disp_cartridge/baijiu,
			/obj/item/chems/chem_disp_cartridge/ogogoro,
			/obj/item/chems/chem_disp_cartridge/orange,
			/obj/item/chems/chem_disp_cartridge/lime,
			/obj/item/chems/chem_disp_cartridge/sodawater,
			/obj/item/chems/chem_disp_cartridge/tonic,
			/obj/item/chems/chem_disp_cartridge/beer,
			/obj/item/chems/chem_disp_cartridge/kahlua,
			/obj/item/chems/chem_disp_cartridge/whiskey,
			/obj/item/chems/chem_disp_cartridge/wine,
			/obj/item/chems/chem_disp_cartridge/vodka,
			/obj/item/chems/chem_disp_cartridge/gin,
			/obj/item/chems/chem_disp_cartridge/rum,
			/obj/item/chems/chem_disp_cartridge/tequila,
			/obj/item/chems/chem_disp_cartridge/vermouth,
			/obj/item/chems/chem_disp_cartridge/cognac,
			/obj/item/chems/chem_disp_cartridge/ale,
			/obj/item/chems/chem_disp_cartridge/mead
		)

/obj/machinery/chemical_dispenser/bar_coffee/full
	spawn_cartridges = list(
			/obj/item/chems/chem_disp_cartridge/coffee,
			/obj/item/chems/chem_disp_cartridge/hot_coco,
			/obj/item/chems/chem_disp_cartridge/milk,
			/obj/item/chems/chem_disp_cartridge/soymilk,
			/obj/item/chems/chem_disp_cartridge/cream,
			/obj/item/chems/chem_disp_cartridge/black_tea,
			/obj/item/chems/chem_disp_cartridge/green_tea,
			/obj/item/chems/chem_disp_cartridge/chai_tea,
			/obj/item/chems/chem_disp_cartridge/red_tea,
			/obj/item/chems/chem_disp_cartridge/ice,
			/obj/item/chems/chem_disp_cartridge/sugar,
			/obj/item/chems/chem_disp_cartridge/syrup_chocolate,
			/obj/item/chems/chem_disp_cartridge/syrup_caramel,
			/obj/item/chems/chem_disp_cartridge/syrup_vanilla,
			/obj/item/chems/chem_disp_cartridge/syrup_pumpkin,
			/obj/item/chems/chem_disp_cartridge/skrianhi,
			/obj/item/chems/chem_disp_cartridge/espresso,
			/obj/item/chems/chem_disp_cartridge/syrup_affelerin,
			/obj/item/chems/chem_disp_cartridge/decafcoffee
		)

/obj/machinery/chemical_dispenser/bar_soft/full
	spawn_cartridges = list(
			/obj/item/chems/chem_disp_cartridge/water,
			/obj/item/chems/chem_disp_cartridge/ice,
			/obj/item/chems/chem_disp_cartridge/cream,
			/obj/item/chems/chem_disp_cartridge/cola,
			/obj/item/chems/chem_disp_cartridge/citrussoda,
			/obj/item/chems/chem_disp_cartridge/cherrycola,
			/obj/item/chems/chem_disp_cartridge/lemonade,
			/obj/item/chems/chem_disp_cartridge/tonic,
			/obj/item/chems/chem_disp_cartridge/sodawater,
			/obj/item/chems/chem_disp_cartridge/lemon_lime,
			/obj/item/chems/chem_disp_cartridge/sugar,
			/obj/item/chems/chem_disp_cartridge/orange,
			/obj/item/chems/chem_disp_cartridge/lime,
			/obj/item/chems/chem_disp_cartridge/watermelon,
			/obj/item/chems/chem_disp_cartridge/europa,
			/obj/item/chems/chem_disp_cartridge/melon,
			/obj/item/chems/chem_disp_cartridge/pineapple,
			/obj/item/chems/chem_disp_cartridge/rootbeer,
			/obj/item/chems/chem_disp_cartridge/afbeer,
			/obj/item/chems/chem_disp_cartridge/hrukhza
		)