#define FOOD_OVERRIDE(type) ##type/icon = 'mods/content/hearthfoods/icons/obj/food_overrides.dmi'
#define INGREDIENTS_OVERRIDE(type) ##type/icon = 'mods/content/hearthfoods/icons/obj/food_ingredients_overrides.dmi'

INGREDIENTS_OVERRIDE(/obj/item/chems/food/rawcutlet)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/cutlet)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/dough)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/doughslice)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/sliceable/flatdough)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/rawmeatball)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/rawsticks)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/bun)
INGREDIENTS_OVERRIDE(/obj/item/chems/food/flatbread)

FOOD_OVERRIDE(/obj/item/chems/food/meatball)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/bread)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/bananabread)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/creamcheesebread)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/meatbread)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/tofubread)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/xenomeatbread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/bread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/meatbread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/tofubread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/xenomeatbread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/creamcheesebread)
FOOD_OVERRIDE(/obj/item/chems/food/slice/bananabread)
FOOD_OVERRIDE(/obj/item/chems/food/cheeseburger)
FOOD_OVERRIDE(/obj/item/chems/food/hamburger)
FOOD_OVERRIDE(/obj/item/chems/food/xenoburger)
FOOD_OVERRIDE(/obj/item/chems/food/tofuburger)
FOOD_OVERRIDE(/obj/item/chems/food/brainburger)
FOOD_OVERRIDE(/obj/item/chems/food/fishburger)
FOOD_OVERRIDE(/obj/item/chems/food/jellyburger)
FOOD_OVERRIDE(/obj/item/chems/food/ghostburger)
FOOD_OVERRIDE(/obj/item/chems/food/spellburger)
FOOD_OVERRIDE(/obj/item/chems/food/mimeburger)
FOOD_OVERRIDE(/obj/item/chems/food/clownburger)
FOOD_OVERRIDE(/obj/item/chems/food/roburger)
FOOD_OVERRIDE(/obj/item/chems/food/bigbiteburger)
FOOD_OVERRIDE(/obj/item/chems/food/superbiteburger)
FOOD_OVERRIDE(/obj/item/chems/food/baguette)
FOOD_OVERRIDE(/obj/item/chems/food/sandwich)
FOOD_OVERRIDE(/obj/item/chems/food/toastedsandwich)
FOOD_OVERRIDE(/obj/item/chems/food/sliceable/pizza)
FOOD_OVERRIDE(/obj/item/chems/food/slice/margherita)
FOOD_OVERRIDE(/obj/item/chems/food/slice/meatpizza)
FOOD_OVERRIDE(/obj/item/chems/food/slice/mushroompizza)
FOOD_OVERRIDE(/obj/item/chems/food/slice/vegetablepizza)
FOOD_OVERRIDE(/obj/item/chems/food/donut)
FOOD_OVERRIDE(/obj/item/chems/food/dionaroast)
FOOD_OVERRIDE(/obj/item/chems/food/sausage)
FOOD_OVERRIDE(/obj/item/chems/condiment/ketchup)
FOOD_OVERRIDE(/obj/item/chems/condiment)

// un-override these until they get new sprites
/obj/item/chems/condiment/vinegar/icon = 'icons/obj/food.dmi'
/obj/item/chems/condiment/small/icon = 'icons/obj/food.dmi'

#undef FOOD_OVERRIDE
#undef INGREDIENTS_OVERRIDE